// AssemblyInfo.cs
// A290/A590 Web Interface Design - Homework Project 2
// Standard assembly metadata file generated by Visual Studio.

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("FunWithVisualStudio")]
[assembly: AssemblyDescription("A290/A590 Homework Project 2 - Fun With Visual Studio ASP.NET Web Site")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Indiana University")]
[assembly: AssemblyProduct("FunWithVisualStudio")]
[assembly: AssemblyCopyright("Copyright 2026")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: ComVisible(false)]
[assembly: Guid("12345678-1234-1234-1234-123456789012")]

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
